# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MZTNetWorkingDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
 
  pod 'ProgressHUD'
  pod 'AFNetworking'  

  # Pods for MZTNetWorkingDemo

  target 'MZTNetWorkingDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MZTNetWorkingDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
